# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20161130_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='e', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='text description default'),
        ),
    ]
